version: "3.1"
services:
  mysql-dev:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: pets
    ports:
      - 4000:3306
    volumes:
      - mysql-dev:/tmp

volumes:
  mysql-dev:
    external: false
